### ISSUE TITLE
JavaScript FAQ

### ISSUE THREAD

**Issue by mmu094** [LinuxEuphony/.github#1]
1 function find_max(nums) {

2 let max_num = Number.NEGATIVE_INFINITY; // smaller than all other numbers

3 for (let num of nums) {

4 if (num > max_num) {

5 // (Fill in the missing line here)

6 }

7 }

8 return max_num;

9 }

Can you solve above missing line ?

**Comment by david-kariuki** [comment]
/**
* @description Function to find maximum number in a number array
* @param nums - number array
* @returns {number}
*/
function find_max(nums) {

    let max_num = Number.NEGATIVE_INFINITY; // smaller than all other numbers

  	// Iterate array
    for (let num of nums) {
      
        // Check if current number in iteration is greater that current max value
        if (num > max_num) {

            max_num = num; // Update largest number
        }
    }

    return max_num; // Return max number
}

**Comment by mmu094** [comment]
Hi, Payoneer helps me run my global business, and I believe Payoneer can help you too. Sign up, try it, and you can get a 25.00 USD reward! Check it out: http://share.payoneer.com/nav/UvmL8kdnO9kv1LNQz38sXWrCwx-OC9-eBSKnrjcZbD0z_8iIFUojOXKbRyrcc_Omzezubl8_geoymoXvOwOGEw2
