### ISSUE TITLE
g.dev/samtaraders

### ISSUE THREAD

**Issue by mmu094** [LinuxEuphony/.github#5]
my_project.console import console

**Comment by david-kariuki** [comment]
Hi, @mmu094 

These discussion sections are meant to discuss issues related to the said repository and not random topics. What message did you intend, maybe, possibly we could resolve to a proper communication method?

**Comment by david-kariuki** [comment]
Hi, @mmu094

These discussion sections are meant to discuss issues related to the said repository and not random topics. What message did you intend, maybe, possibly we could resolve to a proper communication method?

**Comment by mmu094** [comment]
@github @Rizq-Revolution @SamTradersllc @communitybridge @mmu094 
Ceo & Founder
https://rizqshops.com
https://samtraders.com
https://rizqworldwide.comhttps://github.com/mmu094/.mmu094/invitations
https://teams.live.com/l/invite/FAA8RshriGDV1VM8AI

**Comment by mmu094** [comment]
@mmu094
